2024-05-30 16:03:43,969:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:03:54,114:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:03:55,396:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:04:15,548:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/random/anime/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/randoms/views.py", line 29, in get
    serializer = self.get_serializer_class(content)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RandomAnimeView.get_serializer_class() takes 1 positional argument but 2 were given
2024-05-30 16:04:45,189:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/random/anime/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/randoms/views.py", line 29, in get
    serializer = self.get_serializer_class(content)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RandomAnimeView.get_serializer_class() takes 1 positional argument but 2 were given
2024-05-30 16:05:45,605:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/random/anime/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/randoms/views.py", line 29, in get
    serializer = self.get_serializer_class(content)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RandomAnimeView.get_serializer_class() takes 1 positional argument but 2 were given
2024-05-30 16:06:41,617:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:06:44,634:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:06:45,886:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:20:50,443:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:20:53,459:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:20:55,853:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:21:12,776:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/random/manga/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/randoms/views.py", line 27, in get
    content = choice(self.get_queryset())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/random.py", line 347, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
2024-05-30 16:22:54,289:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:22:57,985:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:23:00,051:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:23:09,723:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:23:12,354:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:23:13,851:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:23:19,362:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:23:22,972:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:23:24,648:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:23:30,131:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:23:33,708:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:23:36,208:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:23:41,918:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:23:44,263:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:23:45,400:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:24:13,730:WARNING - django.request log.py (line 241. Not Found: /api/v1/random/manga/)
2024-05-30 16:24:15,089:WARNING - django.request log.py (line 241. Not Found: /api/v1/random/manga/)
2024-05-30 16:24:16,062:WARNING - django.request log.py (line 241. Not Found: /api/v1/random/manga/)
2024-05-30 16:25:59,154:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:26:02,091:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:26:03,597:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:26:18,534:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:26:21,608:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:26:23,255:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:26:36,104:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:26:39,080:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:26:40,795:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:26:54,264:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:26:57,741:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:26:59,517:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:27:07,490:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:27:12,360:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:27:14,485:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:27:24,059:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:27:27,152:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:27:29,499:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:27:36,834:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:27:39,985:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:27:42,328:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:27:55,044:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:27:59,663:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:28:01,657:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:28:08,894:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:28:11,598:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:28:13,323:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:28:37,954:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/views.py changed, reloading.)
2024-05-30 16:28:40,748:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:28:43,088:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:29:00,660:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/urls.py changed, reloading.)
2024-05-30 16:29:02,911:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:29:04,472:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:29:21,290:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/urls.py changed, reloading.)
2024-05-30 16:29:24,340:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:29:26,115:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:29:35,020:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/urls.py changed, reloading.)
2024-05-30 16:29:38,017:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:29:39,735:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:29:45,333:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/urls.py changed, reloading.)
2024-05-30 16:29:48,912:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:29:50,472:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-30 16:30:00,148:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/randoms/urls.py changed, reloading.)
2024-05-30 16:30:03,340:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-30 16:30:05,363:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
